#!/usr/bin/env python3

import argparse
from parler_tts_gguf import ParlerTTSMiniEncoder
from os.path import isdir, dirname


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("--save-path", type=str, required=True, help="the path to save the converted gguf tts model too.")
    parser.add_argument("--voice-prompt", type=str, default="female voice", help="A description of the voice that the model should generate with.")
    return parser.parse_known_args()


if __name__ == '__main__':
    args, _ = parse_arguments()
    if not isdir(dirname(args.save_path)):
        raise ValueError(f"model path, {args.save_path} is not a valid path.")
    ParlerTTSMiniEncoder(args.save_path).write(args.voice_prompt)
